### PR TITLE
GitHub Actions Builds

### PR DESCRIPTION
**Pull request by srivarra**
**If you haven't already, please read through our [contributing guidelines](https://ark-analysis.readthedocs.io/en/latest/_rtd/contributing.html) before opening your PR**

**What is the purpose of this PR?**

Investigating building on GitHub Actions with `cibuildtool`. Trying out Universal (both), arm64 (Apple Silicon), x86_64 (Intel), and whatever else that may be appropriate.

**How did you implement your changes**

Adding a `build.yml` file in `.github/workflows/`.

Added `cibuildwheel` configuration in `pyproject.toml`.

### Current Builds (all on CPython 3.8)

- macOS Builds:
  - Apple Silicon (M1 / M2 / ARM)
  - x86_64 (Intel)
  - universal2 (contains both architectures)
- Windows:
  - x86_64
  - No ARM (Requires Python 3.9 >=)
- Linux:
  - x86_64
  - aarch64 / arm64 (ARM) with QEMU Virtualization

### What Events Trigger Which Jobs?:

The GitHub Action `.github/workflows/build.yml` will run on **3** conditions:
1. When a PR is created and when any additional commit is added to that PR
   1. Runs the following jobs: *`build_wheels`*, *`build_sdist`*
2. When a PR is merged into *`main`*
   1. Runs the following jobs: *`build_wheels`*, *`build_sdist`*
3. When a new Release is created
   1. Runs the following jobs: *`build_wheels`*, *`build_sdist`*, *`test_pypi_publish`*, *`pypi_publish`*

### Order of jobs & steps:

1. **`build_wheels`**
   1. Checkout the current branch with the latest commit
   2. For each OS, build x86_64 and ARM *wheels* (except for Windows ARM, see above) for CPython 3.8
   3. Run tests for x86_64 architectures.
   4. Store the wheel artifacts in `./dist/`, named "distributions" in the interface
2. **`build_sdist`**
   1. Build the Source Distribution with `sdist` on Ubuntu
   2. Validate Source Distribution
   3. Store the Source Distribution artifacts in `./dist/`
3. **`test_pypi_publish`**
    - **NOTE:** Runs only when a new release is created i.e. when the following conditions are met:
    ```yml
    on:
        release:
            types: [created] # When a new release is created
    ```
    and
    ```yml
    if: github.event_name == 'release' && github.event.action == 'published' # a new release is published.
    ```
   - **NOTE:** Requires *`build_wheels`* and *`build_sdist`* to complete successfully before running
    1. Download the artifacts, with the name `distributions` in the `./dist/` directory (i.e. all wheels and the source distribution)
    2. Use [pypa's](https://github.com/pypa) PYPI publish [Github Action](https://github.com/pypa/gh-action-pypi-publish) to the distributions to publish the distributions to TEST_PYPI
4. **`pypi_publish`**
    - **NOTE:** Runs only when a new release is created i.e. when the following conditions are met:
    ```yml
    on:
        release:
            types: [created] # When a new release is created
    ```
    and
    ```yml
    if: github.event_name == 'release' && github.event.action == 'published' # a new release is published.
    ```

    - **NOTE:** Requires *`build_wheels`*, *`build_sdist`*, *`test_pypi_publish`* to complete successfully before running
    1. Download the artifacts, with the name `distributions` in the `./dist/` directory (i.e. all wheels and the source distribution)
    2. Use [pypa's](https://github.com/pypa) PYPI publish [Github Action](https://github.com/pypa/gh-action-pypi-publish) to publish the distributions to PYPI

## CIBuildWheel (`pyproject.toml`)

Let's walk through `pyproject.toml`, there are a lot of additions.

```toml
[build-system]
requires = ["setuptools", "wheel", "numpy>=1,<2", "Cython>=0.29,<1"]
build-backend = "setuptools.build_meta"
```

Identifies the build system to use, and it's requirements.

```toml
[tool.cibuildwheel]
build = [
  "cp38-*"
]
skip = [
    "cp36-*",        # Python 3.6
    "cp37-*",        # Python 3.7
    "cp39-*",        # Python 3.9
    "cp310-*",       # Python 3.10
    "cp311-*",       # Python 3.11
    "*-musllinux_*", # Musllinux
    "pp*",           # PyPy wheels on all platforms
    "*_i686",        # 32bit Linux Wheels
    "*_s390x",       # IBM System/390, "mainframe"
    "*-win32",       # 32bit Windows Wheels
    "*_ppc64le",     # PowerPC
]
```

It's a bit unnecessary for us to build for every platform out there, so we specify only CPython 3.8, and filter out the majority of the other architectures. You may see all the available options [here](https://cibuildwheel.readthedocs.io/en/stable/options/#build-skip)

```toml
[project]
dependencies = ["Cython>=0.29,<1", "numpy>=1,<2", "scipy>=1,<2"]
name = "pyFlowSOM"
authors = [{ name = "Angelo Lab", email = "theangelolab@gmail.com" }]
description = "A Python implementation of the SOM training functionality of FlowSOM"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "Modified Apache License 2.0" }
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "License :: OSI Approved :: Apache Software License",
    "Topic :: Scientific/Engineering :: Bio-Informatics",

]
version = "0.1.13"
urls = { repository = "https://github.com/angelolab/pyFlowSOM" }
```
PEP 621 adds `pyproject.toml` support for all configuration options, the goal is to eliminate `setup.py`. Needed to add this due to using the `version` variable.

```toml
[tool.cibuildwheel]
# Run tests
test-command = "pytest {project}/test"
test-requires = [
    "pytest",
    "pandas",
    "coveralls",
    "pytest-cases",
    "pytest-cov",
    "pytest-mock",
    "pytest-pycodestyle",
    "pytest-randomly",
    "seaborn",
]
build-frontend = "build"
build-verbosity = 3
```
One interesting feature that `cibuildwheel` provides is the ability to test post build. This is enabled currently.

Also note `build-frontend`. The default method to build CPython packages is with `pip`, however [PyPA (Python Packaging Authority)](https://www.pypa.io/en/latest/) recommends using `build`, so we will do so. `build-verbosity` at 3 is the most descriptive therefore making it easier to identify issues.

```toml
[tool.cibuildwheel]
# Avoid testing on emulated architectures
test-skip = [
    "*-win_arm64",               # Skip testing emulated arm64 biulds on Windows
    "*-*linux_aarch64",          # Skip testing emulated Linux builds
    "*-macosx_arm64",            # Skip testing emulated arm64 builds on Intel Macs
    "*-macosx_universal2:arm64", # Skip testing emulated arm64 portion of universal2 builds
]
```
Even though we are not running tests, for future use cases, we should avoid testing on emulated architectures for now as they [cannot be run](https://cibuildwheel.readthedocs.io/en/stable/options/#examples_2).

```toml
# "manylinux" versioning
# PEP 600: https://peps.python.org/pep-0600/
# Build using the manylinux_2_28 image
manylinux-x86_64-image = "manylinux_2_28"
manylinux-aarch64-image = "manylinux_2_28"
```

For building on Linux, Python worked on the ManyLinux project which is designed to unify packages for all major Linux flavors (Ubuntu, Arch, Debian, etc...).
`manylinux_2_28` is the recommended image / platform tagging system.

We are not building for `musllinux` (pronounced muscle linux) as arm versions for `musllinux` take 10x the time that an x86_64 version takes to build. These are generally useful for Alpine Linux (a good distro for Docker images mainly).

```toml
# On an Linux Intel runner with qemu installed, build Intel and aarch64 (arm) wheels
[tool.cibuildwheel.linux]
archs = ["x86_64", "aarch64"]
repair-wheel-command = "auditwheel repair -w {dest_dir} {wheel}"

# Build `universal2` and `arm64` wheels on an Intel runner.
# Note that the `arm64` wheel and the `arm64` part of the `universal2` wheel cannot be tested in this configuration.
[tool.cibuildwheel.macos]
archs = ["x86_64", "arm64", "universal2"]
repair-wheel-command = "delocate-wheel --require-archs {delocate_archs} -w {dest_dir} -v {wheel}"

# Build for Windows x86_64, and ARM 64
[tool.cibuildwheel.windows]
archs = ["AMD64", "ARM64"]
# might not need to repair with delvewheel?
# before-build = "pip install delvewheel"                          # Use delvewheel on windows
# repair-wheel-command = "delvewheel repair -w {dest_dir} {wheel}"
```
Now we specify the actual architectures we wish to build with. In addition specifying the `repair-wheel-command` is useful for packages which depend on external dependencies. You may read more about them [here](https://realpython.com/python-wheels/#bundling-shared-libraries).

Each OS has their own wheel repair utility:
- Linux: [`auditwheel`](https://github.com/pypa/auditwheel)
- macOS: [`delocate-wheel`](https://github.com/matthew-brett/delocate)
- Windows: [`delvewheel`](https://github.com/adang1345/delvewheel) (doesn't work right now for pyFlowSOM for some reason)

```toml
[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::PendingDeprecationWarning",
]
addopts = [
    "-v",
    "-s",
    "--durations=20",
    "--randomly-seed=42",
    "--randomly-dont-reorganize",
    "--cov=pyFlowSOM",
    "--pycodestyle",
]
console_output_style = "count"
```

Use the pytest configuration for the tests.

## Remaining Issues
Just some user experience things to consider for the future:

1. Maybe split the mega workflow into multiple workflows
    1. Just for CI
    2. Builds on new releases
2.  Build for multiple Python versions:
    1.  Python 3.8 (currently used)
    2.  Python 3.9
    3.  Python 3.10
    4.  Python 3.11
    5.  Python 3.12-*pre-release* (just for future proofing)
3.  Add [Dependabot](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions)
    1.  Helps with keeping dependencies up to date.
4. And mainly, well we need to try out a small release and see what changes need to be made.
5. Consider [Hatch](https://hatch.pypa.io/latest/), a Python project manager superior to Poetry, made by the same team who created CIBuildWheel. It works flawlessly with CIBuildWheel.

## Resources + References used
1. [CIBuildWheel Docs](https://cibuildwheel.readthedocs.io/en/stable/)
2. [RealPython - What Are Python Wheels and Why Should You Care?](https://realpython.com/python-wheels/)
3. [Scikit HEP - GHA for Binary Wheels](https://scikit-hep.org/developer/gha_wheels)
4. [PEP 621 - Storing project metadata in pyproject.toml](https://peps.python.org/pep-0621/)
5. Packages which have good implementations for CIBuildWheel:
	a. [black](https://github.com/psf/black)
	b. [NumPy](https://github.com/numpy/numpy)
	c. [scikit-learn](https://github.com/scikit-learn/scikit-learn)

### CODE REVIEW

**Review by ngreenwald — CHANGES_REQUESTED** [review]
This looks great. I agree with your comment about separating out the CI cadence from the build cadence. I don't think we'll need to have wheels built for every commit on a PR. Since we'll need at least 1 release to test things out, I don't think this needs to be changed right away. But once you guys are all comfortable with how this works, I think something like the following would be nice:

Have a single flag somewhere in a config file that controls behavior. The default is that none of this runs. There's a "test" option which, when enabled, causes the wheels build, sdist build, and then runs test_pypi. Once this passes out, we'd be a ready for a new release, and the appropriate logic would trigger based on the release tag. 

I don't think we should get rid of travis until we've migrated the CI over to GA, just to make sure nothing slips through the cracks

**Review by alex-l-kong — COMMENTED** [review]
This is beautiful. A couple of comments:

1. When the time comes to support future Python versions (>=3.9), do we plan to keep support for older versions or deprecate them in the future?
2. It seems like `test_pypi_publish` and `pypi_publish` are set to run concurrently under the same circumstances. Will it be possible to have a workflow/modify this workflow that test uploads to TestPyPI intermediately? I think it'll be good to be able to test `pip`-installability prior to deploying to PyPI. Something like [this](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#publishing-the-distribution-to-pypi-and-testpypi) could work.

**Comment by srivarra** [comment]
@alex-l-kong 

> 1. When the time comes to support future Python versions (>=3.9), do we plan to keep support for older versions or deprecate them in the future?

I think we should follow NumPy, as they tend to stop supporting Python versions 1 higher than the most latest unsupported version. [End of Life Python Versions](https://endoflife.date/python).
> 2. It seems like `test_pypi_publish` and `pypi_publish` are set to run concurrently under the same circumstances. Will it be possible to have a workflow/modify this workflow that test uploads to TestPyPI intermediately? I think it'll be good to be able to test `pip`-installability prior to deploying to PyPI. Something like [this](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#publishing-the-distribution-to-pypi-and-testpypi) could work.

`pypi_publish` requires `test_pypi_publish` to upload without any issues. https://github.com/angelolab/pyFlowSOM/blob/5cffbfd46ab2c4c55367f1e47f3dc452e9ecafcd/.github/workflows/build.yml#L94

They run sequentially. One thing I looked into was having `test_pypi_publish` run for each commit, but it there were some issues when when using [`setuptools_scm`](https://github.com/pypa/setuptools_scm/) which is recommended to use with Test PyPI as you can't upload the same version multiple times on either PyPI or Test PyPI. You can take a look at this [job](https://github.com/angelolab/pyFlowSOM/actions/runs/3944900027/jobs/6751404900) for reference on what I ran into. It wasn't enjoying the name of the files.

**Comment by camisowers** [comment]
Looks solid @srivarra!

**Review by alex-l-kong — APPROVED** [review]

**Review by ngreenwald — CHANGES_REQUESTED** [review]
So one of these GA jobs that says build wheels is actually running pytest?

**Comment by srivarra** [comment]
> So one of these GA jobs that says build wheels is actually running pytest?

@ngreenwald Yeah, here is an example on the ubuntu-latest job. If you open it in a new tab it'll take you to it.

https://github.com/angelolab/pyFlowSOM/actions/runs/4001061334/jobs/6866899974#step:4:372

**Pull request closed without merging**
