### PR TITLE
GitHub Actions Updates, Python 3.9+ Support

### LINKED ISSUE #16: GitHub Actions and Python Version Updates
**Is your feature request related to a problem? Please describe.**
Update the CI to match the other angelolab repos, and we should support Python 3.9+ as NumPy will not make updates available for Python 3.8 anymore.

**Describe the solution you'd like**
Change the CI to be the same as mibi-bin-tools, and add Python 3.9+ wheels.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by srivarra**
**If you haven't already, please read through our [contributing guidelines](https://ark-analysis.readthedocs.io/en/latest/_rtd/contributing.html) before opening your PR**

**What is the purpose of this PR?**

Closes #16. Updates the GitHub Actions workflows to be in line with mibi-bin-tools.

**How did you implement your changes**

Modified the `pyproject.toml` to allow for Python 3.9+ builds. Added tests for all OSes. Updated the `tox.ini`, and moved the pytest config to `pyproject.toml`.

Updated the `setup.py` file to be similar to the one found in `mibi-bin-tools` and `ark`, with a few tweaks to properly apply the Cython compiler directives. Specified the `cyFlowSOM` imports in `__init__.py` instead of loading everything the `cyFlowSOM` module (would also load `numpy` and `scipy`)

**Remaining issues**

Commented out all testing / CI for coverage until there is a solution which works completely. A couple of things I've tried are using the Release Candidate of Cython, which gets coverage to run, but causes it to crash after a file is finished. We'll just wait and see for any developments. I'll make an issue describing this and solutions I've tried.

### CODE REVIEW

**Review by ngreenwald — CHANGES_REQUESTED** [review]
You can re-request from me once Alex and Cami are satisfied

**Review by alex-l-kong — APPROVED** [review]
Cool stuff

**Review by camisowers — APPROVED** [review]

**Review by cliu72 — APPROVED** [review]
I'm not totally sure how to test these changes, but I was able to do `pip install .` so I guess that's enough?

After migrating to python 3.9, is it no longer possible to use python 3.8?

**Comment by srivarra** [comment]
@cliu72

> I'm not totally sure how to test these changes, but I was able to do `pip install .` so I guess that's enough?

Yeah just running the installation is good enough, there's no changes to the logic / algorithm itself.

> After migrating to python 3.9, is it no longer possible to use python 3.8?

Correct, the _minimum_ supported Python version will be 3.9 with the next release.

**Comment by srivarra** [comment]
@ngreenwald

**Review by ngreenwald — APPROVED** [review]

**Pull request merged**
